### ISSUE TITLE
Issue in the server console

### ISSUE THREAD

**Issue by Taknax** [mactso/VillagersRespawn#2]
I am using VillagerRespawn-1.16.5-1.36.0.4 on my server with forge 36.2.30. I got this in my server console: [https://pastebin.com/Qek1dYtS](url).
Can i ignore that?

**Comment by mactso** [comment]
Ah-  That means the update.json file needs to be updated or has a typo from the last update.
You can ignore the error.  It's more of a warning.  It is only happening once on startup right?

Sorry for the delay responding- been working on my taxes.

**Comment by mactso** [comment]
Okay, I was missing an entry for 1.18.2 in the update.json file.
It should be fixed now.

**Comment by Taknax** [comment]
I am gonna test this night and tell you the result.

**Comment by mactso** [comment]
Thank you!   I appreciate your feedback and engagement!
