### ISSUE TITLE
[1.16.5] Deaths via explosion cause a crash with array index out of bounds

### ISSUE THREAD

**Issue by NighthowlerStudios** [mactso/VillagersRespawn#3]
https://pastebin.com/iWQMeS6h

**Comment by mactso** [comment]
Thanks!   I'll test this now.

**Comment by mactso** [comment]
Okay, testing didn't duplicate the error.   I blew up several villagers repeatedly.

I do see how that code could fail if the villager level is an "impossible" value, it would crash so I can bulletproof it.

**Comment by mactso** [comment]
I've "mod version 6" with code to protect against the explosion edge case for approval for minecraft 1.16.3-1.16.5.
