### ISSUE TITLE
[1.16.5] Villagers have a high chance of respawning in a wall

### ISSUE THREAD

**Issue by NighthowlerStudios** [mactso/VillagersRespawn#4]
Please add some code that avoids this.  vanilla bed placement inside village structures is almost always against a wall, and if the house is facing a specific direction, the villager assigned to it will almost always spawn inside the wall.

**Comment by mactso** [comment]
I'll look at this when I'm in the for 1.19.4 update.  Should be soon now.

**Comment by NighthowlerStudios** [comment]
not helpful for the version my modpack is stuck in :/ oh well.  thanks anyway.

**Comment by mactso** [comment]
Completely understand.  I have one more mod to get to 1.19.4 then I'll look into this next.  Not sure why the villagers are having particular problems in your town.   I may need to do additional scanning.   I'll update this ticket again after the problem is addressed.

**Comment by mactso** [comment]
Okay, I've fixed this for 1.16.3,1.16.4, 1.16.5.

I'm implementing the fix in 1.18.2 and 1.19.4 now.

**Comment by NighthowlerStudios** [comment]
Awesome, glad to hear it.  I'll reinclude the mod as soon as possible.  Feel free to close when you wish :)

**Comment by NighthowlerStudios** [comment]
fix seems to be working for me so far, thanks again for updating the older port

**Comment by mactso** [comment]
Glad to help, 

I appreciate the report.  This was probably happening to others as well.
Cheers and Happy Minecrafting,
Two Guys,
MacTso
